version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
      - checkout
      - run: go test -v -mod=vendor -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-workflow:
    jobs:
      - build