version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go test -v -mod=vendor ./...
      - run: go build -mod=vendor -v -ldflags ${ldflags} -o ./puti
workflows:
  version: 2
  build-workflow:
    jobs:
      - build