version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v -mod=vendor ./...
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -v -ldflags ${ldflags} -o ./puti
workflows:
  version: 2
  build-workflow:
    jobs:
      - build