runmode: debug                 # 开发模式, debug, release, test
addr: :8000                  # HTTP绑定端口
name: puti              # API Server的名字
url: http://127.0.0.1:8000   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: putidemojwtseCrect013keyideO

tls:
  https_open: false
  addr: 8080
  cert: configs/server.crt
  key: configs/server.key

# 日志配置
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: logs/server.log
  logger_format_text: false # true为json格式
  rollingPolicy: size # aily 和 size；daily 则根据天进行转存，如果是 size 则根据大小进行转存
  log_rotate_date: 1  # rotate 转存时间，配 合rollingPolicy: daily 使用
  log_rotate_size: 1024 # rotate 转存大小，配合 rollingPolicy: size 使用
  log_backup_count: 7 # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数

# 数据库配置
db:
  name: db_puti
  addr: mysql:3306 # host:port
  username: putiroot
  password: puti123456

