name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Go build
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

    - name: Copy config file and run go test
    - run: |
      cp ./configs/config.yaml.example  ./configs/config.yaml
      go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage
      if: ${{ success() }}
      run: bash <(curl -s https://codecov.io/bash)
